// This file is AUTO-GENERATED by generate_rtl.py – DO NOT EDIT
// Generated from isa_db.json
  // default assignments (avoid latches)
  ctrl = '0;
  ctrl.illegal = 1'b1;

  // LUI
  if (instr[6:0] == 7'b0110111 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.imm_type = U_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
  end

  // AUIPC
  if (instr[6:0] == 7'b0010111 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.imm_type = U_TYPE;
    ctrl.alu_op   = ALU_ADD;
    ctrl.wb_en = 1'b1;
  end

  // JAL
  if (instr[6:0] == 7'b1101111 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.imm_type = J_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.branch = BR_ALWAYS;
    ctrl.link   = 1'b1;
  end

  // JALR
  if (instr[6:0] == 7'b1100111 && instr[14:12] == 3'b000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.branch = BR_ALWAYS;
    ctrl.link   = 1'b1;
  end

  // BEQ
  if (instr[6:0] == 7'b1100011 && instr[14:12] == 3'b000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = B_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.branch = BR_EQ;
  end

  // BNE
  if (instr[6:0] == 7'b1100011 && instr[14:12] == 3'b001 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = B_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.branch = BR_NE;
  end

  // BLT
  if (instr[6:0] == 7'b1100011 && instr[14:12] == 3'b100 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = B_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.branch = BR_LT;
  end

  // BGE
  if (instr[6:0] == 7'b1100011 && instr[14:12] == 3'b101 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = B_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.branch = BR_GE;
  end

  // BLTU
  if (instr[6:0] == 7'b1100011 && instr[14:12] == 3'b110 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = B_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.branch = BR_LTU;
  end

  // BGEU
  if (instr[6:0] == 7'b1100011 && instr[14:12] == 3'b111 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = B_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.branch = BR_GEU;
  end

  // LB
  if (instr[6:0] == 7'b0000011 && instr[14:12] == 3'b000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_LOAD;
    ctrl.mem_width = BYTE;
    ctrl.mem_unsigned = False ;
  end

  // LH
  if (instr[6:0] == 7'b0000011 && instr[14:12] == 3'b001 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_LOAD;
    ctrl.mem_width = HALF;
    ctrl.mem_unsigned = False ;
  end

  // LW
  if (instr[6:0] == 7'b0000011 && instr[14:12] == 3'b010 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_LOAD;
    ctrl.mem_width = WORD;
    ctrl.mem_unsigned = False ;
  end

  // LBU
  if (instr[6:0] == 7'b0000011 && instr[14:12] == 3'b100 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_LOAD;
    ctrl.mem_width = BYTE;
    ctrl.mem_unsigned = True ;
  end

  // LHU
  if (instr[6:0] == 7'b0000011 && instr[14:12] == 3'b101 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_LOAD;
    ctrl.mem_width = HALF;
    ctrl.mem_unsigned = True ;
  end

  // SB
  if (instr[6:0] == 7'b0100011 && instr[14:12] == 3'b000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = S_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_STORE;
    ctrl.mem_width = BYTE;
  end

  // SH
  if (instr[6:0] == 7'b0100011 && instr[14:12] == 3'b001 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = S_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_STORE;
    ctrl.mem_width = HALF;
  end

  // SW
  if (instr[6:0] == 7'b0100011 && instr[14:12] == 3'b010 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = S_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_STORE;
    ctrl.mem_width = WORD;
  end

  // ADDI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_ADD;
    ctrl.wb_en = 1'b1;
  end

  // SLTI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b010 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_SLT;
    ctrl.wb_en = 1'b1;
  end

  // SLTIU
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b011 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_SLTU;
    ctrl.wb_en = 1'b1;
  end

  // XORI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b100 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_XOR;
    ctrl.wb_en = 1'b1;
  end

  // ORI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b110 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_OR;
    ctrl.wb_en = 1'b1;
  end

  // ANDI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b111 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_AND;
    ctrl.wb_en = 1'b1;
  end

  // SLLI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b001 && instr[31:25] == 7'b0000000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_SLL;
    ctrl.wb_en = 1'b1;
  end

  // SRLI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b101 && instr[31:25] == 7'b0000000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_SRL;
    ctrl.wb_en = 1'b1;
  end

  // SRAI
  if (instr[6:0] == 7'b0010011 && instr[14:12] == 3'b101 && instr[31:25] == 7'b0100000 && instr[31:20] == 12'b1) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = I_TYPE;
    ctrl.alu_op   = ALU_SRA;
    ctrl.wb_en = 1'b1;
  end

  // ADD
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b000 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_ADD;
    ctrl.wb_en = 1'b1;
  end

  // SUB
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b000 && instr[31:25] == 7'b0100000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_SUB;
    ctrl.wb_en = 1'b1;
  end

  // SLL
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b001 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_SLL;
    ctrl.wb_en = 1'b1;
  end

  // SLT
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b010 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_SLT;
    ctrl.wb_en = 1'b1;
  end

  // SLTU
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b011 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_SLTU;
    ctrl.wb_en = 1'b1;
  end

  // XOR
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b100 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_XOR;
    ctrl.wb_en = 1'b1;
  end

  // SRL
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b101 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_SRL;
    ctrl.wb_en = 1'b1;
  end

  // SRA
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b101 && instr[31:25] == 7'b0100000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_SRA;
    ctrl.wb_en = 1'b1;
  end

  // OR
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b110 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_OR;
    ctrl.wb_en = 1'b1;
  end

  // AND
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b111 && instr[31:25] == 7'b0000000) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_AND;
    ctrl.wb_en = 1'b1;
  end

  // MUL
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b000 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.mul_valid = 1'b1;
  end

  // MULH
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b001 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.mul_valid = 1'b1;
  end

  // MULHSU
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b010 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.mul_valid = 1'b1;
  end

  // MULHU
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b011 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.mul_valid = 1'b1;
  end

  // DIV
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b100 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.div_valid = 1'b1;
  end

  // DIVU
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b101 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.div_valid = 1'b1;
  end

  // REM
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b110 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.div_valid = 1'b1;
  end

  // REMU
  if (instr[6:0] == 7'b0110011 && instr[14:12] == 3'b111 && instr[31:25] == 7'b0000001) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.wb_en = 1'b1;
    ctrl.div_valid = 1'b1;
  end

  // LR_W
  if (instr[6:0] == 7'b0101111 && instr[31:27] == 5'b00010) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_LOAD;
  end

  // SC_W
  if (instr[6:0] == 7'b0101111 && instr[31:27] == 5'b00011) begin
    ctrl.illegal = 1'b0;
    ctrl.rd_addr  = instr[11:7];
    ctrl.rs1_addr = instr[19:15];
    ctrl.rs2_addr = instr[24:20];
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_STORE;
  end

  // ECALL
  if (instr[6:0] == 7'b1110011 && instr[14:12] == 3'b000 && instr[31:20] == 12'b000000000000) begin
    ctrl.illegal = 1'b0;
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
  end

  // EBREAK
  if (instr[6:0] == 7'b1110011 && instr[14:12] == 3'b000 && instr[31:20] == 12'b000000000001) begin
    ctrl.illegal = 1'b0;
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
  end

  // FENCE
  if (instr[6:0] == 7'b0001111 && instr[14:12] == 3'b000) begin
    ctrl.illegal = 1'b0;
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_FENCE;
  end

  // FENCE_I
  if (instr[6:0] == 7'b0001111) begin
    ctrl.illegal = 1'b0;
    ctrl.imm_type = R_TYPE;
    ctrl.alu_op   = ALU_COPY;
    ctrl.mem_op    = MEM_FENCE_I;
  end
  else begin
    ctrl.illegal = 1'b1;
  end
