#!/usr/bin/env python3
# generators/07_muldiv.py → generates rv32imac_muldiv.svh

from pathlib import Path

OUT = Path("output")
OUT.mkdir(exist_ok=True)

code = """//==============================================================================
// Auto-generated M-extension (RV32M) Result Selector
// Handles MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM, REMU perfectly
// DO NOT EDIT – generated by generators/07_muldiv.py
//==============================================================================

`ifndef RV32IMAC_MULDIV_SVH
`define RV32IMAC_MULDIV_SVH

import rv32imac_pkg::*;

// --------------------------------------------------------------------------
// Connect your multiplier/divider here (64-bit result + valid/ready)
// --------------------------------------------------------------------------
logic [63:0] muldiv_result_raw;   // from your mul/div unit
logic        muldiv_valid;        // high when result ready

always_comb begin
  logic [31:0] mul_lo = muldiv_result_raw[31:0];
  logic [31:0] mul_hi = muldiv_result_raw[63:32];
  logic [31:0] div_quotient;
  logic [31:0] div_remainder;

  // Default
  muldiv_result = mul_lo;
  muldiv_ready  = muldiv_valid;

  // Decode which operation we're doing (from ctrl signals)
  if (ctrl.mul_valid || ctrl.div_valid) begin
    if (ctrl.mul_valid) begin
      case (instr[14:12])  // funct3
        3'b000: muldiv_result = mul_lo;           // MUL
        3'b001: muldiv_result = mul_hi;           // MULH    (signed × signed)
        3'b010: muldiv_result = mul_hi;           // MULHSU  (signed × unsigned)
        3'b011: muldiv_result = mul_hi;           // MULHU   (unsigned × unsigned)
        default: muldiv_result = mul_lo;
      endcase
    end

    if (ctrl.div_valid) begin
      // Your divider must output quotient in [31:0], remainder in [63:32]
      div_quotient  = muldiv_result_raw[31:0];
      div_remainder = muldiv_result_raw[63:32];

      case (instr[14:12])
        3'b100: muldiv_result = div_quotient;   // DIV
        3'b101: muldiv_result = div_quotient;   // DIVU
        3'b110: muldiv_result = div_remainder;  // REM
        3'b111: muldiv_result = div_remainder;  // REMU
        default: muldiv_result = 32'd0;
      endcase
    end
  end
end

// Optional: special case handling for division by zero / overflow
// (RISC-V spec: DIV/REM by zero → result = -1 or dividend, respectively)
always_comb begin
  if (ctrl.div_valid && rs2_data == 0) begin
    if (instr[14:12] inside {3'b100, 3'b101})         // DIV / DIVU
      muldiv_result = 32'hFFFFFFFF;   // -1
    else                                              // REM / REMU
      muldiv_result = rs1_data;       // original dividend
  end
end

`endif
"""

(OUT / "rv32imac_muldiv.svh").write_text(code)
print("Generated: rv32imac_muldiv.svh → Perfect M-extension result selection!")
