#!/usr/bin/env python3
# generators/09_ctrl_struct.py → generates ctrl_struct.svh

from pathlib import Path

OUT = Path("output")
OUT.mkdir(exist_ok=True)

code = """// generated/ctrl_struct.svh
// DO NOT EDIT – auto-generated by generators/09_ctrl_struct.py
`ifndef CTRL_STRUCT_SVH
`define CTRL_STRUCT_SVH

import rv32imac_pkg::*;

//==========================================================================
// Master control structure – one signal for everything in the pipeline
//==========================================================================
typedef struct packed {
  // ── Basic instruction info ─────────────────────────────────────
  logic        illegal;
  logic        compressed;        // 1 if original instr was 16-bit
  logic [4:0]  rd_addr;
  logic [4:0]  rs1_addr;
  logic [4:0]  rs2_addr;

  // ── Immediate type (from decoder) ─────────────────────────────
  logic [2:0]  imm_type;          // 0=I, 1=S, 2=B, 3=U, 4=J

  // ── ALU & operands ───────────────────────────────────────────
  alu_op_t     alu_op;
  logic        alu_src1_pc;       // 1 → use PC instead of rs1
  logic        alu_src2_imm;      // 1 → use immediate instead of rs2

  // ── Memory ───────────────────────────────────────────────────
  mem_op_t     mem_op;            // NONE/LOAD/STORE/FENCE
  mem_width_t  mem_width;         // BYTE/HALF/WORD
  logic        mem_unsigned;      // 1 → zero-extend loads

  // ── Writeback ────────────────────────────────────────────────
  logic        wb_en;             // write rd
  logic        wb_src_mem;        // 1 → load data, 0 → ALU/result

  // ── Branch / Jump ────────────────────────────────────────────
  branch_t     branch;
  logic        link;              // JAL/JALR → write PC+4 to rd/ra
  logic        branch_taken;      // actual taken (EX stage sets this)

  // ── M-extension ──────────────────────────────────────────────
  logic        mul_valid;
  logic        div_valid;
  logic  [1:0] muldiv_res_sel;    // 00=lo, 01=hi_signed, 10=hi_unsigned, 11=rem

  // ── A-extension (atomics) ───────────────────────────────────
  logic        atomic_lr;
  logic        atomic_sc;
  logic  [3:0] atomic_op;         // future AMOs: swap/add/and/or/xor...

  // ── System / CSR ─────────────────────────────────────────────
  logic        csr_read;
  logic        csr_write;
  logic        csr_set;
  logic        csr_clear;
  logic [11:0] csr_addr;
  logic        ecall;
  logic        ebreak;
  logic        mret;
  logic        wfi;

  // ── Exception / Trap ─────────────────────────────────────────
  logic        exception;
  logic  [3:0] exception_code;    // see mcause encoding

  // ── Fence ───────────────────────────────────────────────────
  logic        fence_i;
  logic        fence;

} ctrl_t;

//==========================================================================
// Helper parameters – use these in your decoder generator
//==========================================================================
localparam logic [2:0] IMM_I = 3'd0;
localparam logic [2:0] IMM_S = 3'd1;
localparam logic [2:0] IMM_B = 3'd2;
localparam logic [2:0] IMM_U = 3'd3;
localparam logic [2:0] IMM_J = 3'd4;

`endif
"""

(OUT / "ctrl_struct.svh").write_text(code)
print("Generated: ctrl_struct.svh  – The Heart of Your Core")
